### ISSUE TITLE
does not compile with stable Rust 2018

### ISSUE THREAD

**Issue by myk3v** [vernonrj/codesearch-rs#2]
Great idea of porting code search to Rust. Would attempt it myself if you would not have done that already. Works well for me so far.

However, your current version does not compile with current 2018 stable release channel. If you can't live without unstable features, I suggest documenting the use of the nightly channel and tell to compile with `cargo +nightly install ...`

**Comment by vernonrj** [comment]
I don't think I had this compiling with stable rust, but the only thing it needed nightly for was simd, which is available in stable rust now.

It shouldn't be too difficult to get it compiling on stable.
